### ISSUE TITLE
Evolution CE 3.1.12 and simple Webuser-Login

### ISSUE THREAD

**Issue by cimt** [evocms-community/evolution#147]
I need a simple Webuser-Login for a protected download area!
Formlister-Login works with Evo.1.4! Unfortunately not with Evo 3x!?

It's not possible to install **Composer** on my small webhosting... and don't work with it either (I'm not a dev)

**How can I bring this to run manually or is there another possibility or a plugin?**:
MODxAPI from https://github.com/Pathologic/MODxAPI
Bridge from https://github.com/Pathologic/evo-doctrine-bridge

Honestly... even with Composer I wouldn't be able to install!

Would be really grateful for a little support!

**Comment by cimt** [comment]
Hi  @Pathologic,
i'll ask my question differently and hope for a short answer:
Will EVO 3.x only (or partially) be used with Composer in the future???

Would be very important for me to know... Thanks!

**Comment by Pathologic** [comment]
Will EVO 3.x only (or partially) be used with Composer in the future??? - Yes, but it's your decision how to use composer.

If you cannot use composer with your hosting, then create local copy of your site, run composer commands you need and then upload core/vendor folder to your hosting.

**Comment by cimt** [comment]
Thanks for your answer.
It's not the answer i was hoping for, but good to know! 
I'll continue to do my old websites with 1.4 until they no longer work!!!

**Comment by BBloke** [comment]
Originally v3 was based upon v1.4.  v3 has moved on to a single user model for front and back end.  Obviously migrating from v1.4 to v3 with this model requires a doctrine and modxapi.

With v3 single user model surely these packages should be there by default so the user can have an option to change the model in the FormLister call?  Otherwise how will anyone use v3 with users without it?  Or am I missing something!

**Comment by nick0** [comment]
> With v3 single user model surely these packages should be there by default so the user can have an option to change the model in the FormLister call? Otherwise how will anyone use v3 with users without it?

+100

The beautiful thing about Evo 1.4.x, and what separates Evo from other content management systems, is the ability for non technical users to do some pretty powerful things with snippets - including front end 'web user' login. 

Evo 3.x changed all that in necessitating Bridge and MODxAPI with Composer for front end web user login.

I know that decision was made in the previous Evo 3 branch and out of your hands but please build in some level of backwards compatibility to enable easy front end 'web user' login capability without requiring Composer and technical skills. 

That way non technical users can confidently move 1.4.x sites to 3.1.x and continue to work with Snippets in this awesome CMS.

The Evo community is small enough as it is without losing non technical users due to increased technical requirements.

If making Bridge and MODxAPI default like @BBloke suggests is the way to simply enable front end web user login without having to deal with Composer, please do so.

Thanks and keep up the great work.

**Comment by Pathologic** [comment]
> Originally v3 was based upon v1.4. v3 has moved on to a single user model for front and back end. Obviously migrating from v1.4 to v3 with this model requires a doctrine and modxapi.
> 

That's not right. Modxapi is needed for compatibility with old code. There are new APIs to work with users in 3.x, but there are no ready to use old styled (chunks and snippets) solutions, though it's not too hard to create new FormLister controllers using new APIs. https://github.com/webber12/evocms-user - here is a try, but it's developed in new style with controllers and blade templates.

**Comment by Pathologic** [comment]
> The beautiful thing about Evo 1.4.x, and what separates Evo from other content management systems, is the ability for non technical users to do some pretty powerful things with snippets - including front end 'web user' login.

You don't see the flipside of the coin - it's very hard to develop complex things in 1.4.x especially for new developers, that's why pretty powerful things and snippets are rare as well as skillful developers to create them.

**Comment by Pathologic** [comment]
By the way, my personal opinion is that we need to pay more attention to non-technical users, but there's a lack of resources and developers 🤷‍♂️.

**Comment by cimt** [comment]
@Pathologic i appreciate your work, no question, I even get it as a gift.
I help as much as I can, i translate, test and report bugs... but unfortunately i'm not a programmer and they are needed here!

With Clipper it was the other way round, there weren't enough users and it was discontinued!

What remains important is that we can (may) talk about it, and that's good! Thank you

**Comment by nick0** [comment]
> > The beautiful thing about Evo 1.4.x, and what separates Evo from other content management systems, is the ability for non technical users to do some pretty powerful things with snippets - including front end 'web user' login.
> 
> You don't see the flipside of the coin - it's very hard to develop complex things in 1.4.x especially for new developers, that's why pretty powerful things and snippets are rare as well as skillful developers to create them.

Fair enough. It would be nice to appease Evo users of all technical abilities, no doubt challenging to keep everyone happy.

Thank you for your efforts as always.

**Comment by Pathologic** [comment]
Well, I've decided to add modxapi to vendor libs.

**Comment by cimt** [comment]
Hello Pathologic,

Does that mean, i don't need a composer for webuser login!?
If so, I would be the happiest Evo-User ever :-)

**Comment by nick0** [comment]
> Well, I've decided to add modxapi to vendor libs.

Fantastic news! Thank you so much.

**Comment by Pathologic** [comment]
https://github.com/evocms-community/evolution/commit/6959c63b1b43b4a905a5c02a34eb6994d30dccb6

**Comment by cimt** [comment]
@Pathologic didn't realize it was already working
with developer version CE 3.1.13
**thank you very much for your commitment!**
